import './normalize.css'
import './fonts.css'
import './variables.css'
import './utils.css'
import './globals.css'

import './components/main.css'
import './components/documents.css'
import './components/footer.css'
import './components/announcementlist.css'
import './components/admin.css'